name: voice_gpt
description: a new flutter and chatgpt project
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  avatar_glow: ^3.0.1
  speech_to_text: ^6.5.1
  http: ^1.1.2
  flutter_dotenv: ^5.1.0
  flutter_bloc: ^8.1.3
  lottie: ^2.7.0
  flutter_svg: ^2.0.9 
  sqflite: ^2.3.0
  neumorphic_ui: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
  - .env
  - assets/animations/
  - assets/fonts/
  - assets/svgs/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf